name: Linux binary build
on:
  release:
    types:
      - created
jobs:
  build:
    name: Compile
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
      GO111MODULE: 'on'
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Setup Go
        uses: actions/setup-go@v3.0.0
        with:
          go-version: '^1.18.0'
      - name: Download dependencies
        run: go mod download
      - name: Build binary
        id: compile
        run: go build -o ./gaf
      - name: Upload artifact
        if: steps.compile.outcome == 'success'
        uses: actions/upload-artifact@v3.0.0
        with:
          name: gaf
          path: gaf
          retention-days: 1
  